### PR TITLE
updated index.html, index.js and new index.css

### PR DESCRIPTION
**Pull request by shnfox**
updated index.html, index.js and created new index.css for lesson-4-4

### CODE REVIEW

**Comment by Eightyeightdays** [comment]
- Here you are setting the styles for the `h2` element in the experience section, except that you have already applied the same styles to all `h1` and `h2` elements:

```
#experienceSection h2 {
    color: 555;
    font-size: 18pt;
    margin: 0px;
}
```

You're also doing it here too:

```
#skillsSection h2 {
    color: 555;
    font-size: 18pt;
}
```

- Remember that hex color values have to begin with the # symbol like this: `#555`.

You're also making the mistake of styling elements twice when you do this:

```
#skillsSection ul li{
    font-family: Arial, Helvetica, sans-serif;
    margin: 10px 0;
    padding: 10px;
    background-color: #f7f7f7;
    border: 1px solid #ddd;
    border-radius: 10px;
}
```

```
li {
    margin: 10px 0;
    padding: 10px;
    background-color: #f7f7f7;
    border: 1px solid #ddd;
    border-radius: 10px;
}
```

- For the skills section you are selecting and styling the list items, but then you are also styling **all list items** with the same features which makes the first part redundant. See line 37 of your css file.


- This part is also redundant for the same reason:

```
#messages ul li{
    margin: 10px 0;
    padding: 10px;
    background-color: #f7f7f7;
    border: 1px solid #ddd;
    border-radius: 10px;
}
```

- When you use a selector like this: 
`#messages ul li {}`
you are selecting the list items that are the children of a ul that is the child of the element with an id=messages. To make it simpler you can just use `#messages li {}` which selects all list items that are descendants of (can be found inside) the message element.

- You are setting the font family to Arial, with a fallback to Helvetica and then sans-serif here:
```
#skillsSection ul li{
    font-family: Arial, Helvetica, sans-serif;
}
```

but you have already set the font-family of the body element to Arial, so this is not necessary.

- You set the font size for the labels to 16px, but **the default font size of any html document before any styles have been set is 16px**, so this has no effect. You'd need to change it to something else in order to tick off this task from the list.

- I would advise against mixing different units of measurement, so instead of setting font-size in some places using `pt`, and in others using `px`, just use `px` for example. What I do is to use `rem` everywhere. `rem` is relative to the font size of the document, so in the case where we haven't changed the default font-size of 16px, 1rem = 16px, and 2rem = 32px etc. You can also use fractional amounts like 1.5rem. Using rem makes it simple to apply uniform styles across your page, because you can use it to set padding and margins as well.
Here's more on rem: https://www.sitepoint.com/understanding-and-using-rem-units-in-css/

- Instead of doing this: 
```
input[type="text"],
input[type="email"],
textarea {}
```

you could just select all input elements and textarea elements, because your page doesn't contain any other input type at the moment. Your code is useful if you had checkbox inputs that you wanted to style differently for example, but in this case it's unnecessary.
```

input,
textarea { }
```

- Because you have given your removeButton elements a position of absolute, it means that when the message text is long, it disappears behind the button itself. See if you can find a solution that allows the buttons to sit to the right, while showing all the text clearly.

**Comment by shnfox** [comment]
Thank you for the review,
I will make these updates tonight after work.
And make a new pull request.
I will email when complete.

Thanks
Jason Fox

**Comment by shnfox** [comment]
updated all files per review checkpoints

**Comment by shnfox** [comment]
Not sure if you get emails from the comments in the pull requests, but I
have updated the index.html, index.js, and index.css files per your review
notes.

thanks
Jason

**Comment by Eightyeightdays** [comment]
The new styles look good. You can go ahead and merge when you're ready.

Here's what I updated to make your button sit a bit nicer:

```
#messages li {
    position: relative;
    padding-right: 6rem;
}

#removeButton {
    background-color: red;
    color: white;
    border-radius: 10px;
    font-size: .8rem;
    border: none;
    padding: 5px 10px;
    position: absolute;
    right: 0.5rem;
    bottom: 0;
    top: 0;
    margin: auto 0;
    height: max-content;
}
```
JF

You can alter the code to position the button at the top or bottom instead of at the side if you wish. Here's an article on centring elements that have absolute positioning: https://www.freecodecamp.org/news/how-to-center-an-absolute-positioned-element/

**Comment by shnfox** [comment]
Ok thank you. I thought that the float fixed it pretty good when I tested
it. I used Lorem ipsum up to about 100 words and it sat in the bottom right
every time.

Either way,
Thanks again,
Jason

**Comment by Eightyeightdays** [comment]
The button was overlapping when I tested it, and seeing as you've consistently done well throughout the course I thought you could refine things even more to bring it up to standard! :)
Here's the effect I got initially:
JF - Messages

**Comment by shnfox** [comment]
I see the issues now with your tests. I appreciate the help.

**Pull request merged**
