### PR TITLE
updated all files for lesson-4-5

### PR DESCRIPTION
**Pull request by shnfox**
index.html, index.css updated to reflect changes for lesson-4-5
uploaded js file even though nothing changed.

### CODE REVIEW

**Comment by Eightyeightdays** [comment]
- Make sure that the hrefs in your nav bar anchors correspond to the element ids that they are supposed to link to. At the moment only the skills and messages buttons work.

- The flex property on your `experience-item` class doesn't have any effect because you also have to set `display: flex;`
- The `experience-item` class has a `flex` property that doesn't work properly because there is a slight error in how you wrote the `calc( )` function.

- There is a scrollbar appearing at the bottom of your page which is unnecessary. Look at the attached image for a hint, and see what different options you have for fixing it.
JF

- The padding in your header causes the content to sit off-center, and the buttons get slightly cut off between 500px and 540px width.

If you're using VS Code there's an extension you can add called Code Spell Checker. This is particularly useful if we happen to write an id or class name wrong in one place, but correctly in another.

**Comment by shnfox** [comment]
Thank you for the review. I will look at this as soon as I get home from
work later tonight.

Jason

**Comment by shnfox** [comment]
I have updated the project per the review. Please let me know if there is
anything else you see.
I have to take my time when doing this I think. The JS stuff I was good
with but the CSS stuff I think I feel rushed with so much going on. Thanks
for the reviews and the feedback.

Jason

**Comment by Eightyeightdays** [comment]
There's a lot of stuff going on once you combine all of the HTML, JavaScript and CSS that you guys have been learning so don't worry if it feels a bit much. CSS can be a bit of a headache so what I do is give different elements temporary background colours so I can visually differentiate them on the page. Then I can see how things like padding and margins affect them more easily, and I can see if I'm actually changing the thing I want to change. When I'm finished I comment out the colours.

The changes you've made are good, so you can merge this when you need to.

**Pull request merged**
