### PR TITLE
second commit

### PR DESCRIPTION
**Pull request by shnfox**
Lesson 3-1 
Fingers Crossed this works!

### CODE REVIEW

**Comment by Eightyeightdays** [comment]
I think that with the current structure of your page, the About, Experience and Connect sections would make sense to be wrapped in `<section>` tags. [Here's more on those](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section).

Instead of using a `<h1>` tag for each section, I'd suggest using `<h2>`. This is because it is recommended to only use a single `<h1>` tag per page for the page title, which is important for SEO and accessibility. You can read more about this [here](https://ahrefs.com/blog/h1-tag/).

Your pull request description should describe the changes you have made to your code.

**Comment by shnfox** [comment]
Thank you, I will make these changes and resubmit.

**Comment by Eightyeightdays** [comment]
You can go ahead and merge these latest changes.

**Comment by shnfox** [comment]
Thank you so much
I really appreciate you giving me those notes. It made me take notice that
I was simply just following along  and not thinking of the bigger picture
for the assignment.

Jason

**Comment by Eightyeightdays** [comment]
You're welcome. I actually made a mistake with marking the 3-1 assignment, because I thought that the course material had explained html, so when I saw it in your file I assumed that it's what was asked, when in fact they just wanted you to put your raw information there. Anyway, you're ahead of things, so that's not a problem, and you can safely merge this branch now.
Good job.

**Pull request merged**
